{ username, pkgs, config, ... }: {

  imports = [
    ./hardware-configuration.nix  # generated by nixos-generate-config; do not edit
  ];

  networking.hostName = "nixos-desktop";

  # ── Bootloader ────────────────────────────────────────────────────────────
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = false;  # do not write to NVRAM
  # efiInstallAsRemovable is not needed on desktop (internal drive, known NVRAM)
  # but keeping canTouchEfiVariables = false is safe practice
  boot.loader.efi.efiSysMountPoint = "/boot";

  # ── GPU ───────────────────────────────────────────────────────────────────
  # Intel iGPU (PCI:0:2:0) + Nvidia GTX 1060 (PCI:1:0:0)
  # Monitors are on the Nvidia card. Tell KWin to use it directly via
  # KWIN_DRM_DEVICES; skip PRIME sync (not supported by 535 legacy driver).

  services.xserver.videoDrivers = [ "nvidia" ];
  hardware.nvidia.modesetting.enable = true;
  hardware.nvidia.powerManagement.enable = true;
  hardware.nvidia.open = false;
  hardware.nvidia.nvidiaSettings = true;
  hardware.nvidia.package = config.boot.kernelPackages.nvidiaPackages.legacy_535;
  hardware.graphics.enable = true;
  boot.kernelParams = [ "nvidia-drm.modeset=1" ];

  # Force KWin to render on the Nvidia card (stable PCI path, avoids
  # the broken Intel→Nvidia PRIME copy path that caused 20Hz rendering).
  environment.variables.KWIN_DRM_DEVICES = "/dev/dri/by-path/pci-0000:01:00.0-card";

  # Wait for Nvidia DRM device before starting display manager
  systemd.services.display-manager.after = [ "dev-dri-card2.device" ];
  systemd.services.display-manager.wants = [ "dev-dri-card2.device" ];

  # ── Desktop environment ───────────────────────────────────────────────────
  services.xserver.enable = true;
  services.displayManager.sddm.enable = true;  # login screen
  services.desktopManager.plasma6.enable = true;

    # ── Remove KDE Apps ─────────────────────────────────────────────────────
  environment.plasma6.excludePackages = with pkgs.kdePackages; [
    elisa        # music player
    gwenview     # image viewer
    okular       # PDF viewer (you have zathura)
    kate         # text editor (you have neovim)
    kmail        # email (you have thunderbird)
    konqueror
    korganizer
    kontact
  ];

  # ── Sound ─────────────────────────────────────────────────────────────────
  services.pulseaudio.enable = false;
  security.rtkit.enable = true;
  services.pipewire = {
    enable = true;
    alsa.enable = true;
    alsa.support32Bit = true;
    pulse.enable = true;
  };

  # ── User ──────────────────────────────────────────────────────────────────
  users.users.${username} = {
    isNormalUser = true;
    extraGroups = [ "wheel" "networkmanager" "audio" "video" ];
    initialPassword = "changeme";  # change with passwd after first boot
    group = username;
  };
  users.groups.${username} = {};

  system.stateVersion = "25.05";

  # ── Sudo ───────────────────────────────────────────────────────────────────
  security.sudo.extraRules = [{
    users = [ "thijmen" ];
    commands = [{
      command = "/run/current-system/sw/bin/nvim";
      options = [ "NOPASSWD" ];
    }
    {
      command = "/run/current-system/sw/bin/nixos-rebuild";
      options = [ "NOPASSWD" ];
    }];
  }];


  # ── Force Language to be good ────────────────────────────────────────────────
  environment.sessionVariables = {
    LANG = "en_GB.UTF-8";
    LC_CTYPE = "en_GB.UTF-8";
    LC_COLLATE = "en_GB.UTF-8";
    LC_MESSAGES = "en_GB.UTF-8";
  };

} # End of function.
