{ username, pkgs, config, ... }: {

  imports = [
    ./hardware-configuration.nix  # generated by nixos-generate-config; do not edit
  ];

  networking.hostName = "nixos-desktop";

  # ── Bootloader ────────────────────────────────────────────────────────────
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = false;  # do not write to NVRAM
  # efiInstallAsRemovable is not needed on desktop (internal drive, known NVRAM)
  # but keeping canTouchEfiVariables = false is safe practice
  boot.loader.efi.efiSysMountPoint = "/boot";

  # ── GPU ───────────────────────────────────────────────────────────────────
  # Hardware: Intel iGPU (PCI:0:2:0) = card1, Nvidia GTX 1060 (PCI:1:0:0) = card2
  # Monitors are physically connected to the Nvidia card.
  #
  # DO NOT enable hardware.nvidia.prime.reverseSync — it crashes the legacy_535
  # driver at KWin startup (tested: gen 52 with PRIME enabled → blank screen).
  #
  # DO NOT wait for dev-dri-card2.device — the Nvidia DRM card (card2) with
  # nvidia-drm.modeset=1 initializes slowly; systemd times out waiting for it
  # and the display-manager never starts (tested: gens 52, 63, 64 → boot hang).
  # Use card1 (Intel iGPU) instead: it appears almost instantly, and by the
  # time it's up the Nvidia card is also ready. KWIN_DRM_DEVICES handles routing.
  #
  # DO NOT add intel-media-driver to hardware.graphics.extraPackages without PRIME —
  # it was only needed for the PRIME offload path which we don't use.
  #
  # DO NOT set KWIN_DRM_DEVICES — pointing KWin directly at the Nvidia card via
  # /dev/dri/by-path/pci-0000:01:00.0-card causes KWin to crash on session start
  # and returns the user to the SDDM login screen (tested: gens 52, 63, 64, 65).
  # KWin auto-detects the correct card without this variable.

  services.xserver.videoDrivers = [ "nvidia" ];
  hardware.nvidia.modesetting.enable = true;
  hardware.nvidia.powerManagement.enable = true;
  hardware.nvidia.open = false;
  hardware.nvidia.nvidiaSettings = true;
  hardware.nvidia.package = config.boot.kernelPackages.nvidiaPackages.legacy_535;
  hardware.graphics.enable = true;
  boot.kernelParams = [ "nvidia-drm.modeset=1" ];

  # Wait for Intel iGPU (card1) — NOT card2 (Nvidia). card1 appears fast;
  # card2 with modesetting is too slow and causes display-manager to hang on boot.
  systemd.services.display-manager.after = [ "dev-dri-card1.device" ];
  systemd.services.display-manager.wants = [ "dev-dri-card1.device" ];

  # ── Desktop environment ───────────────────────────────────────────────────
  services.xserver.enable = true;
  services.displayManager.sddm.enable = true;  # login screen
  services.desktopManager.plasma6.enable = true;

    # ── Remove KDE Apps ─────────────────────────────────────────────────────
  environment.plasma6.excludePackages = with pkgs.kdePackages; [
    elisa        # music player
    gwenview     # image viewer
    okular       # PDF viewer (you have zathura)
    kate         # text editor (you have neovim)
    kmail        # email (you have thunderbird)
    konqueror
    korganizer
    kontact
  ];

  # ── Sound ─────────────────────────────────────────────────────────────────
  services.pulseaudio.enable = false;
  security.rtkit.enable = true;
  services.pipewire = {
    enable = true;
    alsa.enable = true;
    alsa.support32Bit = true;
    pulse.enable = true;
  };

  # ── User ──────────────────────────────────────────────────────────────────
  users.users.${username} = {
    isNormalUser = true;
    extraGroups = [ "wheel" "networkmanager" "audio" "video" ];
    initialPassword = "changeme";  # change with passwd after first boot
    group = username;
  };
  users.groups.${username} = {};

  system.stateVersion = "25.05";

  # ── Sudo ───────────────────────────────────────────────────────────────────
  security.sudo.extraRules = [{
    users = [ "thijmen" ];
    commands = [{
      command = "/run/current-system/sw/bin/nvim";
      options = [ "NOPASSWD" ];
    }
    {
      command = "/run/current-system/sw/bin/nixos-rebuild";
      options = [ "NOPASSWD" ];
    }];
  }];


  # ── Force Language to be good ────────────────────────────────────────────────
  environment.sessionVariables = {
    LANG = "en_GB.UTF-8";
    LC_CTYPE = "en_GB.UTF-8";
    LC_COLLATE = "en_GB.UTF-8";
    LC_MESSAGES = "en_GB.UTF-8";
  };

} # End of function.
