{ username, pkgs, ... }: {

  imports = [
    ./hardware-configuration.nix  # generated by nixos-generate-config; do not edit
  ];

  networking.hostName = "nixos-desktop";

  # ── Bootloader ────────────────────────────────────────────────────────────
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = false;  # do not write to NVRAM
  # efiInstallAsRemovable is not needed on desktop (internal drive, known NVRAM)
  # but keeping canTouchEfiVariables = false is safe practice
  boot.loader.efi.efiSysMountPoint = "/boot";

  # ── GPU ───────────────────────────────────────────────────────────────────
  # Uncomment the block matching your GPU:

  # AMD:
  # hardware.opengl.enable = true;
  # hardware.opengl.driSupport = true;

  # Nvidia (proprietary):
  # services.xserver.videoDrivers = [ "nvidia" ];
  # hardware.nvidia.modesetting.enable = true;
  # hardware.nvidia.powerManagement.enable = false;
  # hardware.nvidia.open = false;
  # hardware.nvidia.nvidiaSettings = true;

  # ── Desktop environment ───────────────────────────────────────────────────
  services.xserver.enable = true;
  services.displayManager.sddm.enable = true;  # login screen
  services.desktopManager.plasma6.enable = true;

  # ── Sound ─────────────────────────────────────────────────────────────────
  hardware.pulseaudio.enable = false;
  security.rtkit.enable = true;
  services.pipewire = {
    enable = true;
    alsa.enable = true;
    alsa.support32Bit = true;
    pulse.enable = true;
  };

  # ── User ──────────────────────────────────────────────────────────────────
  users.users.${username} = {
    isNormalUser = true;
    extraGroups = [ "wheel" "networkmanager" "audio" "video" ];
    initialPassword = "changeme";  # change with passwd after first boot
    group = username;
  };
  users.groups.${username} = {};

  system.stateVersion = "25.05";
}
